spring.application.name=ProjetoFDP
spring.datasource.url=jdbc:mysql://localhost:3306/projetoPET
spring.datasource.username=root
spring.datasource.password=09181719
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true